# Generated by Django 3.2.8 on 2021-11-15 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'NameDataBase',
                'verbose_name_plural': 'NameDataBases',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(db_column='Имя товара', max_length=200, verbose_name='Имя товара')),
                ('price', models.IntegerField(db_column='Цена', help_text='Цена', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('star', models.PositiveIntegerField(db_column='Звезды', help_text='Звезды', validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Звезды')),
                ('rating', models.IntegerField(db_column='Рейтинг', help_text='Рейтинг', verbose_name='Рейтинг')),
                ('shot_description', models.CharField(db_column='Краткое описание', help_text='Краткое описание', max_length=200, verbose_name='Краткое описание')),
                ('details_description', models.TextField(db_column='Полное описание', help_text='Полное описание', verbose_name='Полное описание')),
                ('image_product', models.ImageField(db_column='Фото товара', help_text='Фото товара', upload_to='photo/%Y/%m/%d/', verbose_name='Фото товара')),
                ('data_create', models.DateField(auto_now_add=True, db_column='Дата создания', verbose_name='Дата создания')),
                ('data_update', models.DateTimeField(auto_now=True, db_column='Дата обновления', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-price'],
            },
        ),
    ]
