# Generated by Django 3.2.8 on 2021-10-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdb',
            name='name',
            field=models.TextField(db_column='Наименование товара', default='name'),
            preserve_default=False,
        ),
    ]
