# Generated by Django 3.2.8 on 2021-10-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_testdb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'NameDataBase',
                'verbose_name_plural': 'NameDataBases',
                'ordering': ['pk'],
            },
        ),
        migrations.DeleteModel(
            name='TestDb',
        ),
    ]
