# Generated by Django 3.2.8 on 2021-10-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211025_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=200, verbose_name='Имя товара')),
                ('shot_description', models.CharField(help_text='Краткое описание', max_length=200, verbose_name='Краткое описание')),
                ('details_description', models.TextField(help_text='Полное описание', verbose_name='Полное описание')),
                ('data_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
