# Generated by Django 3.2.8 on 2021-10-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20211025_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(db_column='Рейтинг', default=0, help_text='Рейтинг', verbose_name='Рейтинг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.PositiveIntegerField(db_column='Звезды', default=0, help_text='Звезды', verbose_name='Звезды'),
            preserve_default=False,
        ),
    ]
