# Generated by Django 3.2.8 on 2021-10-27 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20211027_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.PositiveIntegerField(db_column='Звезды', help_text='Звезды', validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Звезды'),
        ),
    ]
