# Generated by Django 3.2.8 on 2021-10-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_product_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shot_description',
            field=models.CharField(db_column='Краткое описание', help_text='Краткое описание', max_length=3, verbose_name='Краткое описание'),
        ),
    ]
