# Generated by Django 3.2.8 on 2021-10-29 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_product_shot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(db_column='Цена', default=0, help_text='Цена', validators=[django.core.validators.MinLengthValidator(0)], verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='shot_description',
            field=models.CharField(db_column='Краткое описание', help_text='Краткое описание', max_length=200, verbose_name='Краткое описание'),
        ),
    ]
