# Generated by Django 3.2.8 on 2021-10-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.ImageField(db_column='Фото товара', default=b'', help_text='Фото товара', upload_to='', verbose_name='Фото товара'),
            preserve_default=False,
        ),
    ]
