# Generated by Django 3.2.8 on 2021-11-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_product_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_binary_file',
            field=models.BinaryField(db_column='Файл', default=b'', help_text='Файл', verbose_name='Файл'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(db_column='Фото товара', help_text='Фото товара', upload_to='photo/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
