# Generated by Django 3.2.8 on 2021-11-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20211104_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='test_binary_file',
            field=models.FileField(db_column='Файл', help_text='Файл', upload_to='', verbose_name='Файл'),
        ),
    ]
