# Generated by Django 3.2.8 on 2021-11-04 11:51

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_product_test_binary_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='test_binary_file',
            field=models.FileField(db_column='Файл', help_text='Файл', upload_to=myapp.models.user_directory_path, verbose_name='Файл'),
        ),
    ]
