# Generated by Django 3.2.8 on 2021-11-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_product_test_binary_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test_binary_file',
        ),
    ]
